const CACHE='bozo-one-v5';
const refreshVersion=s=>(s.match(/const APP_VERSION\s*=\s*['"](\d{4}-\d{2}-\d{2}\.\d+(?:-one)?)['"]/)||[])[1];   // the one app's builds say '-one' after the number (docs/plans/SINGLE-APP-STAGE2.md, Stage 2b slice 2, redesign)
const refreshNewer=(a,b)=>{const[x,n]=a.split('.'),[y,m]=b.split('.');return x>y||(x===y&&parseInt(n,10)>=parseInt(m,10))};
const refreshHit=async(c,v)=>{for(const key of[self.registration.scope,new URL('index.html',self.registration.scope).href]){const hit=await c.match(key);if(hit?.ok&&refreshVersion(await hit.clone().text())===v)return hit}};
self.addEventListener('message',e=>{if(e.data?.type!=='bp-refresh'||!e.ports?.[0])return;const port=e.ports[0];e.waitUntil((async()=>{let timer;try{const scope=self.registration.scope;if(!e.source?.url?.startsWith(scope)||!/^\d{4}-\d{2}-\d{2}\.\d+(?:-one)?$/.test(e.data.v))throw Error('wrong scope');const abort=new AbortController();timer=setTimeout(()=>abort.abort(),10000);const vr=await fetch(new Request(new URL('version.json?t='+Date.now(),scope),{cache:'no-store',signal:abort.signal}));if(!vr.ok)throw Error('version');const v=(await vr.json()).v;if(!/^\d{4}-\d{2}-\d{2}\.\d+(?:-one)?$/.test(v))throw Error('version');if(!refreshNewer(v,e.data.v)){port.postMessage({ok:false,reason:'rollback'});return}const c=await caches.open(CACHE);if(v===e.data.v&&await refreshHit(c,v)){port.postMessage({ok:true,v});return}const page=await fetch(new Request(new URL('index.html?bp-prepare='+Date.now(),scope),{cache:'reload',signal:abort.signal}));if(!page.ok||refreshVersion(await page.clone().text())!==v)throw Error('page not ready');await c.put(new URL('__refresh__',scope).href,page.clone());await c.put(scope,page.clone());await c.put(new URL('index.html',scope).href,page);port.postMessage({ok:true,v})}catch(x){port.postMessage({ok:false})}finally{clearTimeout(timer)}})())});
const ASSETS=['./','./index.html','./manifest.json','./icon.svg'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS.map(a=>new Request(a,{cache:'reload'})))).then(()=>self.skipWaiting()))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k.startsWith('bozo-one-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',e=>{
  if(e.request.method!=='GET')return;
  const url=new URL(e.request.url);
  if(url.origin!==location.origin)return;
  if(e.request.mode==='navigate'&&url.searchParams.has('bp-refresh')){e.respondWith((async()=>{const c=await caches.open(CACHE),hit=await c.match(new URL('__refresh__',self.registration.scope).href);if(hit&&refreshVersion(await hit.clone().text())===url.searchParams.get('bp-refresh')){await c.delete(new URL('__refresh__',self.registration.scope).href).catch(()=>{});return hit}const cached=await refreshHit(c,url.searchParams.get('bp-refresh'));if(cached)return cached;const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),10000);try{const r=await fetch(new Request(e.request,{cache:'reload',signal:abort.signal}));return r.status<400?r:(await c.match(url.origin+url.pathname))||(await c.match(self.registration.scope))||r}catch(x){return(await c.match(url.origin+url.pathname))||(await c.match(self.registration.scope))||Response.error()}finally{clearTimeout(timer)}})());return}   // a hosting error (500, 503, 404) is no better than no signal: the copy on the phone opens when there is one
  // network first, always revalidated against the server, cache only as the offline fallback
  const net=fetch(new Request(e.request,{cache:'no-cache'})).then(r=>{if(r.ok&&(!url.search||e.request.mode==='navigate')){const cp=r.clone();caches.open(CACHE).then(c=>c.put(url.search?url.origin+url.pathname:e.request,cp))}return r});   // opening from a notification link keeps the offline copy up to date, one entry per address: one-off links (?t=) used to pile up forever
  if(e.request.mode!=='navigate'){e.respondWith(url.search?net:net.catch(()=>caches.match(e.request,{ignoreSearch:true})));return}
  // weak signal: after 3 s open the copy already on the phone instead of sitting on a blank screen (the app still checks for a newer build once it is up).
  // A hosting error (500, 503, 404) counts as no signal when the phone has the app: its copy opens, and the error is never kept. With no copy, the error shows as before
  e.respondWith(caches.match(e.request,{ignoreSearch:true}).then(hit=>hit?Promise.race([net.then(r=>r.status<400?r:null,()=>null),new Promise(r=>setTimeout(()=>r(null),3000))]).then(r=>r||hit):net));
});
// phone notifications: always show one (iPhones drop subscriptions that stay silent); a tap opens the app
// #12 stage 2 (slice 4): a ping names its league, season, week, person and kind (lg, sid, wid, mid, k: the league adds them). The tap hands
// them to the app (bp-open), which opens exactly that; with no window open, the app's own address carries the season, week and person: a
// one-app ping's (?lg=<that league>), and an older subscription's (?league=<the league's id on this phone>, which the league still sends
// to, so an older ping lands on its own week and says who it was for, as a new one does). A club app's pings name no league: as before
const pingPart=v=>typeof v==='string'&&/^[\w-]{1,64}$/.test(v)?v:'';
const pingAt=(url,x)=>{try{const u=new URL(url,self.registration.scope),q=u.searchParams;if(!x.lg||!(q.get('lg')===x.lg||(q.get('league')&&!q.has('lg')&&u.href.startsWith(self.registration.scope))))return url;for(const k of['sid','wid','mid'])if(x[k])q.set(k,x[k]);return u.href}catch(e){return url}};
self.addEventListener('push',e=>{let d={};try{d=e.data?e.data.json():{}}catch(x){d={body:e.data?e.data.text():''}}
  e.waitUntil(self.registration.showNotification(d.title||'Bozo Parlay',{body:d.body||'',tag:d.tag||undefined,renotify:!!d.tag,icon:new URL('icon-192.png',self.registration.scope).href,data:{url:d.url||self.registration.scope,lg:pingPart(d.lg),sid:pingPart(d.sid),wid:pingPart(d.wid),mid:pingPart(d.mid),k:pingPart(d.k),title:typeof d.title==='string'?d.title.slice(0,120):''}}))});
self.addEventListener('notificationclick',e=>{e.notification.close();const x=e.notification.data||{},url=x.url||self.registration.scope;
  e.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(cs=>{for(const c of cs){if(c.url.startsWith(self.registration.scope)&&'focus'in c){c.postMessage({type:'bp-open',url,lg:x.lg||'',sid:x.sid||'',wid:x.wid||'',mid:x.mid||'',k:x.k||'',title:x.title||''});return c.focus()}}return self.clients.openWindow(pingAt(url,x))}))});
